version: "3.9"
services:
  linktreeapp:
    build: ./
    ports: 
      - "3000:3000"
    environment:
      - CONTENTFUL_SPACE_ID=
      - CONTENTFUL_DELIVERY_TOKEN=
      - CONTENTFUL_PREVIEW_TOKEN=